### ISSUE TITLE
TMS Index

### ISSUE THREAD

**Issue by Maroben** [geometalab/Vector-Tiles-Reader-QGIS-Plugin_2016#1]
calculation of tms index to mercator coordinates.

**Comment by klokan** [comment]
http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/
http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/globalmaptiles.py

**Comment by Maroben** [comment]
thanks, this is very useful
